# Generated by Django 5.2.6 on 2025-09-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('due_date', models.TimeField(blank=True, null=True)),
                ('task_status', models.BooleanField(default=False)),
            ],
        ),
    ]
