# Generated by Django 5.2.6 on 2025-09-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
