# Generated by Django 5.2.6 on 2025-09-25 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_events_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
